<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>db1aff95-bf03-4544-a412-d26fd15704f8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\eshop.ApiService\eshop.ApiService.csproj" />
    <ProjectReference Include="..\eshop.Web\eshop.Web.csproj" />
  </ItemGroup>

</Project>
